# Site settings
title: pascal.io
email: mail@pascal.io

# Build settings
permalink: /:title
excerpt_separator: "\n\n\n"

kramdown:
  input: GFM
coffee:
  style: :compressed
sass:
  sass_dir: css/_sass
  style: :compressed
defaults:
-
  scope:
    path: ""
  values:
    layout: "post"